frontend/models/Thread.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "thread".
 *
 * @property integer $thread_id
 * @property string $title
 * @property integer $thread_starter
 * @property string $created_at
 * @property string $updated_at
 * @property integer $replies
 * @property integer $views
 * @property integer $locked
 * @property string $picture
 * @property string $content
 * @property string $description
 */
class Thread extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'thread';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return 
        [
            [['title','release_date'], 'required'],
            [['title', 'content', 'description', 'release_date', 'genre', 'producers', 'developers', 'composers', 'designers'], 'safe'],
            [['title'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return 
        [
            'thread_id'     => 'Thread ID',
            'title'         => 'Title',
            'username'      => 'Thread Starter',
            //'created_at'  => 'Created At',
            //'updated_at'  => 'Updated At',
            //'replies'     => 'Replies',
            //'views'       => 'Views',
            //'locked'      => 'Locked',
            'genre'         => 'Genre',
            //'content'     => 'Content',
            'description'   => 'Description',
        ];
    }

    public function getUser() # Define the table relatoon ship between User and thread
    {
        return $this->hasOne(User::className(), ['id' => 'thread_starter']);
    }

    public function getPost() # Define the table relatoon ship between Thread and Post
    {
        return $this->hasMany(Post::className(), ['thread_id' => 'thread_id']);
    }


}

class User extends \yii\db\ActiveRecord
{
    
}

frontend/controllers/PostController.php
<?php

namespace frontend\controllers;

use Yii;
use app\models\Post;
use app\models\PostSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PostController implements the CRUD actions for Post model.
 */
class PostController extends Controller
{
    public function behaviors()
    {
        return 
        [
            'verbs' => 
            [
                'class'     => VerbFilter::className(),
                'actions'   => 
                    [
                        'delete' => ['post'],
                    ],
            ],

            'access' => 
            // User+ can create post
            [
                'class' => \yii\filters\AccessControl::className(),
                'only'  => ['create'],
                'rules' => 
                [
                    [
                        'allow' => true,
                        'roles' => ['moderator','user'],
                    ],
                 ],
     
            ],


             // User+ can only edit and delete their own post, unless they are moderator+
            [
                'class' => \yii\filters\AccessControl::className(),
                'only'  => ['update','delete'],
                'rules' => 
                [
                    // allow authenticated users
                    [
                        'allow' => true,
                        'roles' => ['user'],
                    ],
                    // everything else is denied
                ]
            ],   
        ];          
    }

    /**
     * Lists all Post models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Post model.
     * @param integer $post_id
     * @return mixed
     */
    public function actionView($post_id)
    {
        return $this->render('view', [
            'model' => $this->findModel($post_id),
        ]);
    }

    /**
     * Creates a new Post model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($thread_id)
    {
        $model = new Post();

        if ($model->load(Yii::$app->request->post())) 
        {
             $model->post_creator   = Yii::$app->user->identity->id; # Post Creator is the currently logged in id.
             $model->thread_id      = $thread_id;   # Set the corresponding thread_id

             // Manually parses the current datetime
             $model->created_at     = date("Y-m-d H:i:s");
             $model->updated_at     = date("Y-m-d H:i:s");

            if ($model->save()) 
            { 
                return $this->redirect(['thread/view', 'thread_id' => $thread_id]);
            }
        } 

        else 
        {
            return $this->render('create', [
                'model' => $model,
            ]);
        }


    }

    /**
     * Updates an existing Post model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $post_id
     * @return mixed
     */
    public function actionUpdate($post_id)
    {
        $model = $this->findModel($post_id);

        // Manually parses the current datetime
        $model->updated_at = date("Y-m-d H:i:s");

        if (\Yii::$app->user->can('editPost', ['post' => $model])) # RBAC rule validation, since we can't implement this in behavior.
        {
            if ($model->load(Yii::$app->request->post()) && $model->save()) 
            {
                return $this->redirect(['thread/view', 'thread_id' => $model->thread_id]);
            } 

            else 
            {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }

        else
        {
            Yii::$app->session->setFlash('error',Yii::t('user', 'Sorry, you cannot edit this post!'));
            return $this->redirect(['thread/view', 'thread_id' => $model->thread_id]);
        }
    }

    /**
     * Deletes an existing Post model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $post_id
     * @return mixed
     */
    public function actionDelete($post_id)
    {
        $model = $this->findModel($post_id);
        if (\Yii::$app->user->can('editPost', ['post' => $model])) # RBAC rule validation, since we can't implement this in behavior.
        {
            $this->findModel($post_id)->delete();
            return $this->redirect(['thread/view', 'thread_id' => $model->thread_id]);
        }
        else
        {
            Yii::$app->session->setFlash('error',Yii::t('user', 'Sorry, you cannot delete this post!'));
            return $this->redirect(['thread/view', 'thread_id' => $model->thread_id]);
        }
    }

    /**
     * Finds the Post model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $post_id
     * @return Post the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($post_id)
    {
        if (($model = Post::findOne($post_id)) !== null) 
        {
            return $model;
        } 

        else 
        {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/ThreadController.php
<?php

namespace frontend\controllers;

use Yii;
use app\models\Thread;
use app\models\ThreadSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\UploadForm;
use yii\web\UploadedFile;



/**
 * ThreadController implements the CRUD actions for Thread model.
 */
class ThreadController extends Controller
{
    public function behaviors()
    {
        return 
        [
          'verbs' => 
          [
            'class'   => VerbFilter::className(),
            'actions' => 
            [
              'delete' => ['post'],
            ],
          ],

          'access' => 
          // User+ can create thread
          [
            'class' => \yii\filters\AccessControl::className(),
            'only'  => ['create'],
            'rules' => 
            [
              [
                  'allow' => true,
                  'roles' => ['moderator','user'],
              ],
            ],

          ],


           //User+ can only edit and delete their own thread, unless they are moderator+
          [
            'class' => \yii\filters\AccessControl::className(),
            'only'  => ['update','delete'],
            'rules' => 
            [
                // allow authenticated users
                [
                    'allow' => true,
                    'roles' => ['user'],
                ],
                // everything else is denied
            ]
          ],   
        ];          
    }

    /**
     * Lists all Thread models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel  = new ThreadSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel'   => $searchModel,
            'dataProvider'  => $dataProvider,

        ]);
    }

    /**
     * Displays a single Thread model.
     * @param integer $thread_id
     * @return mixed
     */
    /*public function actionView($thread_id)
    {
        return $this->render('view', [
            'model' => $this->findModel($thread_id),
        ]);
    }*/

    /**
     * Creates a new Thread model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {

        $model = new Thread();

        /*--------------------------------------------------------
        if ($model->load(Yii::$app->request->post())) {
          $model->created_at = time();
          $model->updated_at = time();
           if ($model->save()) {             
             return $this->redirect(['view', 'id' => $model->id]);             
           } 
        } 
        return $this->render('create', [
            'model' => $model,
        ]);
        --------------------------------------------------------*/        
        
        if ($model->load(Yii::$app->request->post())) 
        {
          $model->thread_starter  = Yii::$app->user->identity->id; # Thread Starter is the currently logged in id.

          // Manually parses the current datetime
          $model->created_at      = date("Y-m-d H:i:s");
          $model->updated_at      = date("Y-m-d H:i:s");

          $uniqueName             = date("YmdHis"); #Same filename prevention
          $model->picture         = UploadedFile::getInstance($model, 'picture');

          if(UploadedFile::getInstance($model, 'picture') != null) # Only rename the file if there is something to rename at the first place
          {
            $model->picture->name = $uniqueName.$model->picture->name;  
          } 

          if ($model->save()) 
          {      

          if ($model->picture && $model->validate()) 
          {                
              $model->picture->saveAs('images/cover/' . $model->picture->baseName . '.' . $model->picture->extension);
          }       
          return $this->redirect(['view', 'thread_id' => $model->thread_id]);             
          } 
        } 

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Thread model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $thread_id
     * @return mixed
     */
    public function actionUpdate($thread_id)
    {
        
        $model = $this->findModel($thread_id);
        if (\Yii::$app->user->can('editThread', ['post' => $model])) # RBAC rule validation, since we can't implement this in behavior.
        {
          if ($model->load(Yii::$app->request->post())) 
          {
              // Manually parses the current datetime
              $model->updated_at      = date("Y-m-d H:i:s");
              $uniqueName             = date("YmdHis"); #Same filename prevention

              if(UploadedFile::getInstance($model, 'picture') != null) # Only rename the file if there is something to rename at the first place
              {
                $model->picture         = UploadedFile::getInstance($model, 'picture');
                $model->picture->name   = $uniqueName.$model->picture->name;  
              }
              else
              {
                $old_model      = $this->findModel($thread_id);
                $model->picture = $old_model->picture;
              }

              if ($model->save()) 
              { 
                  if ($model->picture && $model->validate()) 
                  {     
                    if(UploadedFile::getInstance($model, 'picture') != null)
                    { 
                      $model->picture->name = $model->picture->name;            
                      $model->picture->saveAs('images/cover/' . $model->picture->baseName . '.' . $model->picture->extension);
                    }     
                  } 
                  return $this->redirect(['view', 'thread_id' => $model->thread_id]);
              }
          }
            
                return $this->render('update', [
                    'model' => $model,
                ]);
        }
        else
        {
            Yii::$app->session->setFlash('error',Yii::t('user', 'Sorry, you cannot edit this thread'));
            return $this->redirect(['view', 'thread_id' => $model->thread_id]);
        }

        
    }

    /**
     * Deletes an existing Thread model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $thread_id
     * @return mixed
     */
    public function actionDelete($thread_id)
    {
        $model = $this->findModel($thread_id);
        if (\Yii::$app->user->can('editThread', ['post' => $model])) # RBAC rule validation, since we can't implement this in behavior.
        {
            $this->findModel($thread_id)->delete();
            return $this->redirect(['index']);
        }
        else
        {
            Yii::$app->session->setFlash('error',Yii::t('user', 'Sorry, you cannot delete this thread'));
            return $this->redirect(['view', 'thread_id' => $model->thread_id]);
        }
    }

    /**
     * Finds the Thread model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $thread_id
     * @return Thread the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($thread_id)
    {
        if (($model = Thread::findOne($thread_id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionView($thread_id)
    {
        return $this->render('view', [
        'model' => $this->findModel($thread_id),
        ]);  

    }
}

frontend/views/thread/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Thread */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="thread-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]) ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'release_date')->widget(\yii\jui\DatePicker::classname(), [
    //'language' => 'ru',
    'dateFormat' => 'yyyy-M-dd',
	]) ?>
    
    <?= $form->field($model, 'genre')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'producers')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'developers')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'composers')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'designers')->textInput(['maxlength' => true]) ?>

    
    <?= $form->field($model, 'picture')->fileInput() ?>


    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/thread/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ThreadSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="thread-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'thread_id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'thread_starter') ?>

    <?= $form->field($model, 'created_at') ?>

    <?= $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'replies') ?>

    <?php // echo $form->field($model, 'views') ?>

    <?php // echo $form->field($model, 'locked') ?>

    <?php // echo $form->field($model, 'picture') ?>

    <?php // echo $form->field($model, 'content') ?>

    <?php // echo $form->field($model, 'description') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/thread/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Thread */

$this->title = 'Create Thread';
$this->params['breadcrumbs'][] = ['label' => 'Threads', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="thread_table forcepad">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/thread/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ThreadSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Threads';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="thread-index">

   
    <h1><?= Html::encode($this->title)." / List of Games" ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Post New Game', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'tableOptions'=>['class'=>'thread_table'],
        'rowOptions' => function ($model, $key, $index, $grid) {
                return [
                            'id'            => $model['thread_id'], 
                            'onclick'       => 'location.href="index.php?r=thread/view&thread_id="+this.id;',
                            'style'         => "cursor: pointer",
                            
                ];
        },
        'columns' => [
           
        //['class' => 'yii\grid\SerialColumn'],
            //'created_at',
            //'updated_at',
            'title',
            'genre',
            'developers',
            //'replies',
            //'views',
            /*[
             'label'=>'Image',
             'format'=>'raw',
             'value' => function ($data) {
                return Html::img($data['picture'],
                    ['width' => '250px']);
            },


             
            ],*/

            
            //'thread_starter',
            //['label'=>'Poster', 'value'=> 'user.username'
            //],


            /*[
             'label'=>'Description',
             'value' => function ($data) {
                return preg_replace('/\s+?(\S+)?$/', '', substr($data['description'], 0, 701));
            },


            ],*/

            /*[
                'class' => 'yii\grid\ActionColumn',
                'urlCreator' => function ($action, $model, $key, $index) {
                    $url ='index.php?r='.$this->context->id.'/'.$action.'&thread_id='.$model->thread_id;
                    return $url;
                }

            ],*/
        ],
    ]); ?>

</div>

frontend/views/thread/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Thread */

$this->title = 'Update Thread: ' . ' ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Threads', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'thread_id' => $model->thread_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="thread_table forcepad">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/thread/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* In the end, i didn't use these widgets because it's too hard to customize
use yii\grid\GridView;
use yii\widgets\ListView;
*/
if(strlen($model->picture)<5) //Default Cover if not set
{
    $model->picture = "no_cover.png";
}
//$user_role = \Yii::$app->user->identity->role;

//if (\Yii::$app->user->can('editThread', ['post' => $model])) {
 //   echo "<br><br><br><br><br>I can edit all post!"; 
//} 

/* @var $this yii\web\View */
/* @var $model app\models\Thread */


$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Threads', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="thread-view">

    
    &nbsp;<kbd>Discussion started by <span class="role_<?= $model->user->role; ?>"><?= $model->user->username; ?></span> on <i><?= date('d F Y',strtotime($model->created_at)); ?></i>. </kbd>


<table class="thread_table">
  <tr valign="top">
    <td width="170">
        <img class="forum_avatar" src="images/avatar/<?php if($model->user->avatar==null){ echo "no_avatar.gif"; } else { echo $model->user->avatar; }; ?>">
        <div class="forum_username role_<?= $model->user->role; ?>"><?= $model->user->username; ?></div>
        <div class="forum_user_details">Join Date: <?= date('M Y',$model->user->created_at); ?><br>
        Posts: -<br>
        Reputation: -<br>
        </div>

    </td>

    <td class="thread_td">
        

        <div class="thread_title"><?= $model->title; ?></div>
        <img class="thread_cover" src="images/cover/<?= $model->picture; ?>">
        <div class="thread_description"><?= $model->description; ?></div>
        <br>
        <div class="thread_info">
        Initial Release Date <br><kbd><?= date('d F Y',strtotime($model->release_date)); ?></kbd><br><br>
        Genres               <br><kbd><?= $model->genre; ?></kbd><br><br>
        Producers            <br><kbd><?= $model->producers; ?></kbd><br><br>
        Developers           <br><kbd><?= $model->developers; ?></kbd><br><br>
        Composers            <br><kbd><?= $model->composers; ?></kbd><br><br>
        Designers            <br><kbd><?= $model->designers; ?></kbd>
        </div><br><br>

    </td>
  </tr>
</table>


    <p>
        <?= Html::a('New Comment', ['post/create', 'thread_id' => $model->thread_id], ['class' => 'btn btn-success forceright']) ?>
        <?= Html::a('Edit Thread', ['update', 'thread_id' => $model->thread_id], ['class' => 'btn btn-primary forceright']) ?>

        <?= Html::a('Delete Thread', ['delete', 'thread_id' => $model->thread_id], [
            'class' => 'btn btn-danger forceright',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

   <br><br>
    <?php foreach ($model->post as $model2) { 
    //echo $model2->content;
        ?>
    
        <div>&nbsp;<kbd>Posted on <?= date('d F Y, h:i:s A',strtotime($model2->created_at)); ?></kbd></div>
    <table class="thread_table">
  <tr valign="top">
    <td width="170">
        <img class="forum_avatar" src="images/avatar/<?php if($model2->user->avatar==null){ echo "no_avatar.gif"; } else { echo $model2->user->avatar; }; ?>">
        <div class="forum_username role_<?= $model2->user->role; ?>"><?= $model2->user->username; ?></div>
        <div class="forum_user_details">Join Date: <?= date('M Y',$model2->user->created_at); ?><br>
        Posts: -<br>
        Reputation: -<br>
        </div>

    </td>

    <td class="thread_td">
        <?= nl2br($model2->content); ?>
    </td>
  </tr>
</table>
        
        
        <?= Html::a('Edit Comment', ['post/update', 'post_id' => $model2->post_id], ['class' => 'btn btn-primary forceright']) ?>

        <?= Html::a('Delete Comment', ['post/delete', 'post_id' => $model2->post_id], [
            'class' => 'btn btn-danger forceright',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    <br><br>
<?php } ?>
</div>