frontend/controllers/ThreadController.php
<?php

namespace frontend\controllers;

use Yii;
use app\models\Thread;
use app\models\ThreadSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\UploadForm;
use yii\web\UploadedFile;



/**
 * ThreadController implements the CRUD actions for Thread model.
 */
class ThreadController extends Controller
{
    public function behaviors()
    {
        return 
        [
          'verbs' => 
          [
            'class'   => VerbFilter::className(),
            'actions' => 
            [
              'delete' => ['post'],
            ],
          ],

          'access' => 
          // User+ can create thread
          [
            'class' => \yii\filters\AccessControl::className(),
            'only'  => ['create'],
            'rules' => 
            [
              [
                  'allow' => true,
                  'roles' => ['moderator','user'],
              ],
            ],

          ],


           //User+ can only edit and delete their own thread, unless they are moderator+
          [
            'class' => \yii\filters\AccessControl::className(),
            'only'  => ['update','delete'],
            'rules' => 
            [
                // allow authenticated users
                [
                    'allow' => true,
                    'roles' => ['user'],
                ],
                // everything else is denied
            ]
          ],   
        ];          
    }

    /**
     * Lists all Thread models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel  = new ThreadSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel'   => $searchModel,
            'dataProvider'  => $dataProvider,

        ]);
    }

    /**
     * Displays a single Thread model.
     * @param integer $thread_id
     * @return mixed
     */
    /*public function actionView($thread_id)
    {
        return $this->render('view', [
            'model' => $this->findModel($thread_id),
        ]);
    }*/

    /**
     * Creates a new Thread model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {

        $model = new Thread();

        /*--------------------------------------------------------
        if ($model->load(Yii::$app->request->post())) {
          $model->created_at = time();
          $model->updated_at = time();
           if ($model->save()) {             
             return $this->redirect(['view', 'id' => $model->id]);             
           } 
        } 
        return $this->render('create', [
            'model' => $model,
        ]);
        --------------------------------------------------------*/        
        
        if ($model->load(Yii::$app->request->post())) 
        {
          $model->thread_starter  = Yii::$app->user->identity->id; # Thread Starter is the currently logged in id.

          // Manually parses the current datetime
          $model->created_at      = date("Y-m-d H:i:s");
          $model->updated_at      = date("Y-m-d H:i:s");

          $uniqueName             = date("YmdHis"); #Same filename prevention
          $model->picture         = UploadedFile::getInstance($model, 'picture');

          if(UploadedFile::getInstance($model, 'picture') != null) # Only rename the file if there is something to rename at the first place
          {
            $model->picture->name = $uniqueName.$model->picture->name;  
          } 

          if ($model->save()) 
          {      

          if ($model->picture && $model->validate()) 
          {                
              $model->picture->saveAs('images/cover/' . $model->picture->baseName . '.' . $model->picture->extension);
          }       
          return $this->redirect(['view', 'thread_id' => $model->thread_id]);             
          } 
        } 

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Thread model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $thread_id
     * @return mixed
     */
    public function actionUpdate($thread_id)
    {
        
        $model = $this->findModel($thread_id);
        if (\Yii::$app->user->can('editThread', ['post' => $model])) # RBAC rule validation, since we can't implement this in behavior.
        {
          if ($model->load(Yii::$app->request->post())) 
          {
              // Manually parses the current datetime
              $model->updated_at      = date("Y-m-d H:i:s");
              $uniqueName             = date("YmdHis"); #Same filename prevention

              if(UploadedFile::getInstance($model, 'picture') != null) # Only rename the file if there is something to rename at the first place
              {
                $model->picture         = UploadedFile::getInstance($model, 'picture');
                $model->picture->name   = $uniqueName.$model->picture->name;  
              }
              else
              {
                $old_model      = $this->findModel($thread_id);
                $model->picture = $old_model->picture;
              }

              if ($model->save()) 
              { 
                  if ($model->picture && $model->validate()) 
                  {     
                    if(UploadedFile::getInstance($model, 'picture') != null)
                    { 
                      $model->picture->name = $model->picture->name;            
                      $model->picture->saveAs('images/cover/' . $model->picture->baseName . '.' . $model->picture->extension);
                    }     
                  } 
                  return $this->redirect(['view', 'thread_id' => $model->thread_id]);
              }
          }
            
                return $this->render('update', [
                    'model' => $model,
                ]);
        }
        else
        {
            Yii::$app->session->setFlash('error',Yii::t('user', 'Sorry, you cannot edit this thread'));
            return $this->redirect(['view', 'thread_id' => $model->thread_id]);
        }

        
    }

    /**
     * Deletes an existing Thread model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $thread_id
     * @return mixed
     */
    public function actionDelete($thread_id)
    {
        $model = $this->findModel($thread_id);
        if (\Yii::$app->user->can('editThread', ['post' => $model])) # RBAC rule validation, since we can't implement this in behavior.
        {
            $this->findModel($thread_id)->delete();
            return $this->redirect(['index']);
        }
        else
        {
            Yii::$app->session->setFlash('error',Yii::t('user', 'Sorry, you cannot delete this thread'));
            return $this->redirect(['view', 'thread_id' => $model->thread_id]);
        }
    }

    /**
     * Finds the Thread model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $thread_id
     * @return Thread the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($thread_id)
    {
        if (($model = Thread::findOne($thread_id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionView($thread_id)
    {
        return $this->render('view', [
        'model' => $this->findModel($thread_id),
        ]);  

    }
}

frontend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;


AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="myBackgroundImage">
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top myNavBar',
        ],
    ]);
    $menuItems = [
        ['label' => 'Home', 'url' => ['/site/index']],
        ['label' => 'Game Discussion', 'url' => ['/thread/index']],
        //['label' => 'About', 'url' => ['/site/about']],
        //['label' => 'Contact', 'url' => ['/site/contact']],
    ];
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Signup', 'url' => ['/user/registration/register']];
        $menuItems[] = ['label' => 'Login', 'url' => ['/user/security/login']];
    } else {
        $menuItems[] = [
            'label' => 'Logout (' . Yii::$app->user->identity->username . ')',
            'url' => ['/site/logout'],
            'linkOptions' => ['data-method' => 'post']
        ];
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer myNavBar">
    <div class="container">
        <p class="pull-left">&copy; Games Discussion Forum - <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>